language: python
python: 3.6
sudo: false

install:
  - pip install mkdocs==1.0.4
  - pip install git+https://github.com/linkchecker/linkchecker.git


script:
  - mkdocs build --clean --site-dir site
  - linkchecker site/index.html --ignore-url="search\.html"

cache: pip
