language: python
python: 
  - "3.6"

sudo: false

install:
  - pip install -r requirements.txt


script:
  - mkdocs build --clean --site-dir site
  - linkchecker site/index.html --ignore-url="search\.html


cache: pip
