language: python
python: 
  - "3.6"

sudo: false

install:
  - pip install -r requirements.txt


script:
  - mkdocs build --clean --site-dir site
  - pylinkvalidate.py --progress --verbose file://$TRAVIS_BUILD_DIR/site/index.html 


cache: pip
