language: python
python: 
  - "3.6"
  - "pypy3"

sudo: false

install:
  - pip install -r requirements.txt


script:
  - mkdocs build --clean --site-dir site
  - pylinkvalidate.py --progress site/index.html


cache: pip
