language: python
python: 3.7
sudo: false

install:
  - pip install mkdocs==1.0.4
  - pip install git+https://github.com/linkchecker/linkchecker.git@htmlparser-beautifulsoup


script:
  - mkdocs build --clean --site-dir site
  - linkchecker site/index.html --ignore-url="search\.html"

cache: pip
