commit_message: '[ci skip]'
files:
  - source: /docs/**/*.*
    ignore:
      - '*.sh'
      - '*.js'
      - '*.css'
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%
  - source: /mkdocs.yml
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%
    type: txt
  - source: /docs_exported
    ignore:
      - '*.js'
      - '*.css'
      - '*.sh'
      - /**/mkdocs.yml
    translation: /translations_exported/%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs_exported/**/mkdocs.yml
    translation: /translations_exported/%two_letters_code%/%original_path%/%original_file_name%
    type: txt
