# If you add a page, you must add it to the index here
pages:
  - Home: 'index.md'
  - Getting Started:
    - Getting Started With Scripts: 'Getting_Started.md'
  - Commands:
    - Commands: 'Vanilla/Commands.md'
  - Brackets:
    - Bracket Handlers: 'Brackets/Brackets.md'
  - Item States:
    - Item Conditions: 'Vanilla/Item_Modification/Item_Conditions.md'
    - Renaming items and setting tooltips: 'Vanilla/Item_Modification/Renaming_Tooltips.md'
  - Ore Dictionary:
    - Ore Dictionary: 'Vanilla/OreDict.md'
  - Advanced Functions:
    - Arrays and Loops: 'AdvancedFunctions/Arrays_and_Loops.md'
    - Calculations: 'AdvancedFunctions/Calculations.md'
    - Contional Statements: 'AdvancedFunctions/Conditional_Statements.md'
    - Custom Functions: 'AdvancedFunctions/Custom_Functions.md'
    - Import: 'AdvancedFunctions/Import.md'
  - Vanilla:
    - Brackets:
      - Items: 'Vanilla/Brackets/Bracket_Item.md'
      - Entities: 'Vanilla/Brackets/Bracket_Entity.md'
      - Liquids: 'Vanilla/Brackets/Bracket_Liquid'
    - Recipes:
      - Crafting Table Recipes: 'Vanilla/Recipes/Recipes_Crafting_Table.md'
      - Furnace Recipes: 'Vanilla/Recipes/Recipes_Furnace.md'
      - Seed Drops: 'Vanilla/Recipes/Seeds.md'
    - Variable Types:
      - Types Overview: 'Vanilla/Variable_Types/Variable_Types.md'
      - IEntityDefinition: 'Vanilla/Variable_Types/IEntityDefinition.md'
      - IIngredient: 'Vanilla/Variable_Types/IIngredient.md'
      - IItemStack: 'Vanilla/Variable_Types/IItemStack.md'
  - Mods:
    - Modtweaker:
      - Modtweaker: 'Mods/Modtweaker/Modtweaker.md'
      - Thermal Expansion:
        - Compactor: 'Mods/Modtweaker/ThermalExpansion/Compactor.md'
        - Crucible: 'Mods/Modtweaker/ThermalExpansion/Crucible.md'
        - InductionSmelter: 'Mods/Modtweaker/ThermalExpansion/InductionSmelter.md'
        - Insolator: 'Mods/Modtweaker/ThermalExpansion/Insolator.md'
        - Pulverizer: 'Mods/Modtweaker/ThermalExpansion/Pulverizer.md'
        - Refinery: 'Mods/Modtweaker/ThermalExpansion/Refinery.md'
        - Sawmill: 'Mods/Modtweaker/ThermalExpansion/Sawmill.md'
      - BetterWithMods:
        - Anvil: 'Mods/Modtweaker/BetterWithMods/Anvil.md'
        - Buoyancy: 'Mods/Modtweaker/BetterWithMods/Buoyancy.md'
        - Cauldron: 'Mods/Modtweaker/BetterWithMods/Cauldron.md'
        - Stoked Cauldron: 'Mods/Modtweaker/BetterWithMods/StokedCauldron.md'
        - Crucible: 'Mods/Modtweaker/BetterWithMods/Crucible.md'
        - Stoked Crucible: 'Mods/Modtweaker/BetterWithMods/StokedCrucible.md'
        - Kiln: 'Mods/Modtweaker/BetterWithMods/Kiln.md'
        - Saw: 'Mods/Modtweaker/BetterWithMods/Saw.md'
        - Turntable: 'Mods/Modtweaker/BetterWithMods/Turntable.md'


# Do not edit in PRs below here
site_name: Crafttweaker Documentation

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs